name: "piwriw_blog"
mode: "dev"
port: 8000
version: "v0.0.1"
start_time: "2023-1-28"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "root"
  dbname: "my_blog"
  max_open_conns: 200
  max_idle_conns: 50
